pushing some work( test has hibernate connection errors)
pushing some work( test has hibernate connection errors)

it breaks on trying to initialize the connection, as far as i can tell it is something about the aws url that it doesn't like.

just run the "shelf test" to see the errors. some quick errors of possible interest:
Cannot get a connection as the driver manager is not properly initialized
...
ERROR: FATAL: database "postgres2" does not exist
...
Caused by: org.hibernate.exception.GenericJDBCException: Error calling DriverManager#getConnection
...
Caused by: org.postgresql.util.PSQLException: FATAL: database "postgres2" does not exist